# Generated by Django 3.2.18 on 2023-03-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_comment_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='title',
            new_name='meal_name',
        ),
    ]
