# Generated by Django 3.2.18 on 2023-03-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_title_meal_meal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='content',
            new_name='description',
        ),
    ]
