# Generated by Django 3.2.18 on 2023-03-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_content_meal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='updated_on',
        ),
    ]
