# Generated by Django 3.2.18 on 2023-03-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_meal_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='meal',
        ),
    ]
