# Generated by Django 3.2.18 on 2023-03-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_rename_post_review_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('size', models.IntegerField(choices=[(2, '2 seats'), (4, '4 seats'), (6, '6 seats')])),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='day',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='booking',
            name='tables',
            field=models.ManyToManyField(to='restaurant.Table'),
        ),
    ]
