# Generated by Django 3.2.18 on 2023-03-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20230320_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='size',
            field=models.IntegerField(choices=[(2, '2 seats'), (4, '4 seats'), (6, '6 seats')], default=2),
        ),
    ]
