# Generated by Django 3.2.18 on 2023-03-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_booking_table_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table_for',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6')], default=1),
        ),
        migrations.AlterField(
            model_name='table',
            name='size',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6')], default=2),
        ),
    ]
