# Generated by Django 3.2.18 on 2023-03-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20230329_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table_for',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6')], default=2),
        ),
    ]
