# Generated by Django 3.2.18 on 2023-03-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_auto_20230329_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table_for',
            field=models.IntegerField(choices=[(2, '2 Guests'), (4, '4 Guests'), (6, '6 Guests')], default=2),
        ),
        migrations.AlterField(
            model_name='table',
            name='size',
            field=models.IntegerField(choices=[(2, '2 Guests'), (4, '4 Guests'), (6, '6 Guests')], default=2),
        ),
    ]
