# Generated by Django 3.2.18 on 2023-03-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_auto_20230329_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tables',
        ),
    ]
