# Generated by Django 3.2.18 on 2023-03-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_remove_booking_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='account',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
