# Generated by Django 3.2.18 on 2023-04-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_booking_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-time']},
        ),
    ]
